---
- name: Install nginx
  yum: name=nginx state=present

- name: Copy default.conf
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx

- name: Copy nginx.conf
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: insert firewalld rule for nginx
  firewalld: port={{ http_port }}/tcp permanent=true state=enabled immediate=yes
  ignore_errors: true

- name: http service state
  service: name=nginx state=started enabled=yes
