---
- name: Install php-fpm and deps
  yum: name={{ item }} state=present
  with_items:
    - php
    - php-mysqlnd
    - php-fpm
    - php-opcache
    - php-gd
    - php-xml
    - php-mbstring
  notify: restart php-fpm

- name: Update php-fpm config file
  replace:
    path: "/etc/php-fpm.d/www.conf"
    regexp: 'apache'
    replace: "nginx"

- name: Update php-fpm config file
  replace:
    path: "/etc/php-fpm.d/www.conf"
    regexp: '127.0.0.1:9000'
    replace: "/run/php-fpm/www.sock"