---
- hosts: wp_centos_vds
  gather_facts: False
  become: true
  vars_files:
    - vars/default.yml
  roles:
    - common
    - nginx
    - php
    - mysql
    - wordpress
    - zabbix_agent
    - firewall

  # environment:
  #   http_proxy: http://10.115.62.1:8080
  #   https_proxy: http://10.115.62.1:8080