---
- hosts: wp_centos
  gather_facts: False
  become: true
  vars_files:
    - vars/default.yml
  roles:
    - common
    - nginx
    - php
    # - mysql
    - wordpress
    - firewall
  # environment:
  #   http_proxy: http://10.115.62.1:8080
  #   https_proxy: http://10.115.62.1:8080