#MySQL Settings
mysql_root_password: "rootpassword"
mysql_db: "wp_database"
mysql_user: "wp_user"
mysql_password: "password"
 
#HTTP Settings
http_host: "wp.example.com"
http_conf: "wp.example.com.conf"
http_port: "80"
zabbix_server_ip: "10.115.62.101"
zabbix_agent_port: "10050"
zabbix_node_name: "node3.alma.103"

## -- PHP configuration -- ##
php_fpm:
  # PHP version to install. Defaults to PHP 7.3.
  version: 7.4