# Firewall Configuration
    - name: Disable SELinux
      selinux:
        state: disabled
 
    # - name: Disable SELinux Without Reboot
    #   command: /sbin/setenforce 0
    - name: Stop and disable firewalld.
      service:
        name: firewalld
        state: stopped
        enabled: False
 
    # - name: Configure Firewall
    #   firewalld: zone=public service=http permanent=yes state=enabled
 
    # - name: Reload Firewall
    #   systemd: name=firewalld state=reloaded