---
- name: Install zaabix repo
  dnf:
    name: 'https://repo.zabbix.com/zabbix/6.0/rhel/8/x86_64/zabbix-agent-6.0.3-1.el8.x86_64.rpm'
    state: present
    disable_gpg_check: true

- name: Install zaabix
  dnf:
    name: zabbix-agent
    state: present

# - name: Change zabbix server IP
#   lineinfile:
#     path: /etc/zabbix/zabbix_agentd.conf
#     regexp: '^Server=127.0.0.1$'
#     line: Server={{ zabbix_server_ip }}
- name: Change zabbix server IP
  lineinfile:
      dest: /etc/zabbix/zabbix_agentd.conf
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
      loop:
        - { regexp: '^Server=127.0.0.1', line: 'Server={{ zabbix_server_ip }}' }
        - { regexp: '^Hostname=Zabbix server', line: 'Hostname={{ zabbix_node_name }}' }
        - { regexp: '^ServerActive=127.0.0.1', line: 'ServerActive={{ zabbix_server_ip }}' }

- name: Insert firewalld rule for zabbix-agent
  firewalld: port={{ zabbix_agent_port }}/tcp permanent=true state=enabled immediate=yes
  ignore_errors: true

- name: http service state
  service: name=zabbix-agent state=started enabled=yes
  