---
- name: Install zaabix repo
  dnf:
    name: 'https://repo.zabbix.com/zabbix/6.0/rhel/8/x86_64/zabbix-agent-6.0.3-1.el8.x86_64.rpm'
    state: present
    disable_gpg_check: true

- name: Install zabbix
  dnf:
    name: zabbix-agent
    state: present

- name: Zabbix-agent configs
  template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: root
    group: root
    mode: '0644'

- name: Insert firewalld rule for zabbix-agent
  firewalld: port={{ zabbix_agent_port }}/tcp permanent=true state=enabled immediate=yes
  ignore_errors: true

- name: http service state
  service: name=zabbix-agent state=started enabled=yes
  